### ISSUE TITLE
English version please

### ISSUE THREAD

**Issue by omega3** [leolee9086/themeEditor#3]
Could you please provide english version of the plugin? I don't know your language and words in the elements of the interface cannot be copied to translator, which makes it unusable.

**Comment by leolee9086** [comment]
Sorry, I am an architect and interior designer, and I have a lot of design work on a daily basis, so I may not be able to respond to issues on GitHub in a timely manner. The new version now offers multi-language options.

**Comment by omega3** [comment]
Thank you.
